### ISSUE TITLE
Question on LocalHistogram and flush()

### ISSUE THREAD

**Issue by algermissen** [pingcap/rust-prometheus#101]
Hi,

at first: thanks for putting this crate together!!

I am wondering about the use of LocalHistgram: it seems I actively have to call flush() from the individual threads, meaning that I have to decide when to actually flush().

Do you think it makes sense to have any local histogram flushed implicitly when metrics are collected? That way one would not have to worry about periodically calling flush().

Does that thinking make sense and would it work to add it to the create at some point in time (mostly asking this to gain understanding not su much as a feature request yet)

UPDATE: I realise this would require registry to know all local histograms which sort of goes against their very reason. I keep the question open in case it is of interest. Please just close.

Thanks

jan

**Comment by siddontang** [comment]
Hi @algermissen 

Why we want to support local histogram is to ensure the best performance for TiKV only, now I have no idea to remove the explicit flush, maybe we can use thread local value later. 

If you have any suggestion, please tell us. Now I will close your issue as you said above. Thank you :-)
