### ISSUE TITLE
Update the crates.io version?

### ISSUE THREAD

**Issue by jedisct1** [pingcap/rust-prometheus#107]
Hi,

The last version published on crates.io is 0.2.8, which doesn't compile any more with current Cargo versions.

Could you publish an update to crates.io?

Thanks!

**Comment by siddontang** [comment]
Thanks @jedisct1 

We will update after #108 merged.

**Comment by siddontang** [comment]
Hi @jedisct1 

We have already updated to 0.3.0, please try it. :-)

**Comment by jedisct1** [comment]
Thanks a lot!
