### ISSUE TITLE
register() in Registry would panic

### ISSUE THREAD

**Issue by algermissen** [pingcap/rust-prometheus#115]
Hi,

just saw that calling register() on a Registry could panic without any possibility for the user to let that error bubble up the chain to be handled gracefully outside the registry (see the call to unnwrap() in https://github.com/pingcap/rust-prometheus/blob/master/src/registry.rs#L203)

Is that intentional? Would it not be better to map over the result of write?

Jan

**Comment by siddontang** [comment]
Hi @algermissen 

The unwrap in the register is for the RwLock.
I think it makes a scene here because in most cases, the lock operation can't fail except we meet some very serious bugs.

**Comment by algermissen** [comment]
Cool.
