### ISSUE TITLE
try to use Core-local Statistics mechanism

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#133]
Now we find that the lock contention of Vector metrics is very serious. To avoid this, we usually implement a local metric mechanism then flush to the global metrics, this works well and has a high performance, but we can't always use this way conveniently in anywhere. 

A better way is to use Core-local Statistics, like RocksDB does http://rocksdb.org/blog/2017/05/14/core-local-stats.html

**Comment by breeswish** [comment]
Duplicate with https://github.com/pingcap/rust-prometheus/issues/102
