### ISSUE TITLE
Provide a IntCounter and IntGauge

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#149]
Mostly, we use the integer for counter and gauge, so it is more efficient to use atomic int64 directly than float64.

**Comment by breeswish** [comment]
prometheus-go implements similar optimizations, but leaving a nicer interface (transparent to users): https://github.com/prometheus/client_golang/commit/ae6939214cd9f7c7a1c511550ac7da1be1c2a924

**Comment by siddontang** [comment]
cool, but we should support math.Trunc, and do a benchmark to compare Trunc + Int Atomic and Float Atomic.

**Comment by breeswish** [comment]
yes. I will do a benchmark. If the performance impact of math.thunc is minimal, I prefer this way.

**Comment by breeswish** [comment]
According to the benchmark, adding a trunc check (and uses float as interface) will slow down about 20%~30% compared to AtomicInt:

test counter::bench_atomic_f64                          ... bench:          11 ns/iter (+/- 2)
test counter::bench_atomic_u64                          ... bench:           4 ns/iter (+/- 0)
test counter::bench_atomic_u64_trunc                    ... bench:           6 ns/iter (+/- 2)

However it is still nearly 50% faster than the AtomicFloat.

**Comment by breeswish** [comment]
According to the rust book,

> Casting from a float to an integer will round the float towards zero.

I guess it is equal to `if (v.round() as u64) as f64 == v`. Will update the benchmark for this later.

**Comment by breeswish** [comment]
Time consumption of these two are exactly the same.

**Comment by breeswish** [comment]
We can implement `Counter<T = f64>` so that by default users have a f64 counter and if necessary a u64 counter can be used.
