### ISSUE TITLE
`Counter.inc_by` should be named as `try_inc_by`

### ISSUE THREAD

**Issue by breeswish** [pingcap/rust-prometheus#151]
It attempts to `inc_by` so that it is `try_inc_by`.

For `inc_by`, it should be coded as `self.try_inc_by(..).unwrap()`.

**Comment by siddontang** [comment]
I suggest using `inc_by` and panic directly internally to make code simple.

**Comment by breeswish** [comment]
Fixed in PR #156, closing.
