### ISSUE TITLE
Incompatibility with protobuf 1.6

### ISSUE THREAD

**Issue by adam-rhebo** [pingcap/rust-prometheus#174]
As indicated by their [Changelog](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md), the `protobuf` crate [dropped the `MessageStatic` trait](https://github.com/stepancheg/rust-protobuf/pull/262) which implies compilation errors in this crate:
```
error[E0432]: unresolved import `protobuf::MessageStatic`
  --> /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.2.3/src/codec.rs:36:35
   |
36 |     use protobuf::{self, Message, MessageStatic};
   |                                   ^^^^^^^^^^^^^ no `MessageStatic` in the root

error[E0433]: failed to resolve. Could not find `MessageStatic` in `protobuf`
   --> /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.4.1/src/../proto/metrics.rs:213:21
    |
213 |         ::protobuf::MessageStatic::descriptor_static(None::<Self>)
    |                     ^^^^^^^^^^^^^ Could not find `MessageStatic` in `protobuf`
```

**Comment by siddontang** [comment]
#171 is fixing this.

**Comment by overvenus** [comment]
Hi @adam-rhebo 

Try upgrading[0] the protobuf to v1.7, I think it has been fix https://github.com/stepancheg/rust-protobuf/issues/289#issuecomment-389929147 .

[0]: `cargo update -p protobuf`

**Comment by adam-rhebo** [comment]
@overvenus Yes, I noticed and hence this can be closed now. (But the merge request is still interesting w.r.t. protobuf 2.0.)
