### ISSUE TITLE
Upgrade to Rust 2018

### ISSUE THREAD

**Issue by brson** [pingcap/rust-prometheus#217]
After TiKV itself is successfully upgraded (https://github.com/tikv/tikv/issues/3896) we can bump prometheus to Rust 2018 as well. Do a major version bump.

**Comment by brson** [comment]
In thinking about backwards compatibility I'm inclined to explicitly break support for Rust 2015 when we do this upgrade - it's possible to be compatible with both, but by doing so we have to be vigilant about breaking 2015 compatibility. I'm inclined to insert some boilerplate code into each of [fail](https://github.com/pingcap/fail-rs/issues/21), [prometheus](https://github.com/pingcap/rust-prometheus/issues/217), and [grpc](https://github.com/pingcap/grpc-rs/issues/256) that is definitely 2018 only and breaks the build under 2015 so we don't have to worry about breaking 2015 compatibility in a minor version bump.

Let me know if anybody is opposed to that.

**Comment by Hoverbear** [comment]
@brson When you get there please investigate using `const fn` in our upgrade:

This is a common use case:

```rust
lazy_static! {
    static ref TIKV_REQUEST_DURATION_HISTOGRAM_VEC: HistogramVec = register_histogram_vec!(
        "tikv_request_duration_seconds",
        "Bucketed histogram of TiKV requests duration",
        &["type"]
    )
}
```

**Comment by brson** [comment]
I have a branch here that does the upgrade https://github.com/brson/rust-prometheus/tree/rust-2018

I have not looked into const fn yet but I will.

**Comment by brson** [comment]
I'm also trying to figure out how far back in the Rust stable toolchain one has to go before cargo starts just ignoring `edition = "2018"`, since that's when it's theoretically possible to be compatible with both 2015 and 2018. I am hopefully though that cargo started rejecting `edition = "2018` at the same time it started accepting `crate` in paths, making it very unlikely to have a single crate that's compatible with Rust 2018 and pre-2018 toolchains.

**Comment by brson** [comment]
The tikv toolchain is upgraded to a version that supports 2018 now, so I think once it's had a few days on master w/o being reverted it's safe to go ahead. I'll do so sometime next week.

**Comment by brson** [comment]
Oh, I haven't done anything with `const fn` in the posted patch yet.

**Comment by brson** [comment]
I don't see any CI here. Not sure if that's a problem or not.

**Comment by Hoverbear** [comment]
@brson This is an issue, nothing to test. :)

**Comment by brson** [comment]
Lol 😆

**Comment by brson** [comment]
Reassigned to @nrc since he has a newer [PR up](https://github.com/pingcap/rust-prometheus/pull/226)

**Comment by breeswish** [comment]
Fixed in https://github.com/pingcap/rust-prometheus/pull/242
