### ISSUE TITLE
registry: namespacing all registered collectors/metrics

### ISSUE THREAD

**Issue by lucab** [pingcap/rust-prometheus#228]
It would be nice to have an additional `prefix` field stored within `Registry`, so that all collectors/metrics registered with it are automatically namespaced with the relevant prefix (when encoding).

The usecase for this is shared/library logic recording internal metrics that are exposed by consuming applications. That is:
 * library counter: `outgoing_requests_total`
 * app0 consumer:
   - registry prefix: `app0`
   - metric name: `app0_outgoing_requests_total`
* app1 consumer:
   - registry prefix: `app1`
   - metric name: `app1_outgoing_requests_total`

This would mimic client-go `WrapRegistererWithPrefix`: https://godoc.org/github.com/prometheus/client_golang/prometheus#WrapRegistererWithPrefix

**Comment by lucab** [comment]
As a side-note, I think there are similar usecases for registry-wide `labels` too.

**Comment by breeswish** [comment]
Good suggestion! Since golang client support this, we should consider this! I will do it when I'm free. Feel free to propose a PR before me.
