### ISSUE TITLE
Panic in debug due to int overflow in collector_id

### ISSUE THREAD

**Issue by jsham** [pingcap/rust-prometheus#236]
**Describe the bug**
Running debug build might crash, due to collector_id overflowing (which is intended!)
This can be fixed by using `std::num::Wrapping` type for hashes.

```thread 'tokio-runtime-worker-1' panicked at 'attempt to add with overflow', /builds/..../_cargo/registry/src/github.com-1ecc6299db9ec823/prometheus-0.5.0/src/registry.rs:97:17```

**Comment by breeswish** [comment]
Thanks for your report!

**Comment by breeswish** [comment]
Fixed in #237
