### ISSUE TITLE
Any new release of prometheus-static-metric?

### ISSUE THREAD

**Issue by n4to4** [pingcap/rust-prometheus#250]
The last release (v0.1.4) was a year ago, and it doesn't compile on stable Rust because of `#![feature(proc_macro)]`, which is not needed for the current Rust versions, and is already removed on the master branch.

**Comment by breeswish** [comment]
Thanks for the reminding. I will update it maybe in a week.

**Comment by breeswish** [comment]
I dig into this issue a little today, looks like you will need `#![feature(proc_macro_hygiene)]` if you want to use static metric register macros like `register_static_counter_vec!`. However if you only use `make_static_metric!` then it will be fine.

**Comment by n4to4** [comment]
I see. Thanks a lot 👍
