### ISSUE TITLE
`--no-default-features --features=push` does not build

### ISSUE THREAD

**Issue by nagisa** [pingcap/rust-prometheus#277]
**Describe the bug**

The crate does not specify its feature dependencies properly.

**To Reproduce**

1. Build this crate with `--no-default-features --features=push` flags

**Expected behavior**

Crate should build.

**Possible resolutions**

One possible option is to add a dependency on `protobuf` feature from the `push` feature. Another is to push the text exposition format, allowing to drop the protobuf code entirely.

**Comment by siddontang** [comment]
> Another is to push the text exposition format, allowing to drop the protobuf code entirely

what do you think @breeswish @overvenus 

IMO, it is better that if we can remove protobuf dependence.

**Comment by breeswish** [comment]
We do have options to remove the protobuf dependency. However currently we are not doing correctly when use the `push` feature.
