### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#28]

**Comment by lucab** [comment]
You may (or may not) be interested in linking to https://docs.rs/prom/.

**Comment by siddontang** [comment]
Thanks @lucab.

But later we will use `prometheus` as crate name, maybe the linking may be changed.

**Comment by lucab** [comment]
Yeah, of course. https://docs.rs/prometheus exists. but it still references the previous one. I just wanted to point out that docs.rs already hosts documentation for you (in case you missed its launch).
