### ISSUE TITLE
Any objections to me merging this into rust metrics

### ISSUE THREAD

**Issue by posix4e** [pingcap/rust-prometheus#41]
I have my own very simple Prometheus implementation. Since yalls is already more baked i would like to switch to it.

**Comment by siddontang** [comment]
Hi @posix4e 
You can use this in your rust metrics, any advice is welcome :-)

**Comment by posix4e** [comment]
One big bit of advice would be to get on an irc room and advertise it. Frankly since y'all are going to to be the way i do prometheus reporting maybe we can share #rust-metrics

**Comment by posix4e** [comment]
Feel free to close this issue whenever
