### ISSUE TITLE
It is not an error for a MetricFamily to have no metrics

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#47]

**Comment by overvenus** [comment]
[text_create.go#L37](https://github.com/prometheus/common/blob/master/expfmt/text_create.go#L37) returns an error if a MetricFamily has no metrics.

It confuses me why go returns an error? 

@brian-brazil

**Comment by brian-brazil** [comment]
This is something that Go happens not to support, but it's valid.

**Comment by overvenus** [comment]
All right, thanks @brian-brazil
