### ISSUE TITLE
more descriptive issues

### ISSUE THREAD

**Issue by Rukenshia** [pingcap/rust-prometheus#52]
I'd really like to contribute since I actually started working on a Prometheus client library some time ago but never got to finish it because I don't have enough time to do this right now. I found this project but the issues here have little to no descriptions or _what actually is needed_.

**Comment by siddontang** [comment]
Hi @Rukenshia 
Thanks for your interest and welcome to contribute! I sorry that we don't have any descriptions or what is needed right now. We will improve these later.

Now, I think the most important issues are #5 , #34 and #7, feel free to have a try :-)
