### ISSUE TITLE
use Atomic value to improve performance

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#59]
Now we use `RwLock<f64>`, but we can use Atomic U64 like golang client to improve the performance. 

But be careful that now the stable rust only supports AtomicUsize, so we must use this in 64 bit system only. 

And we should do benchmark to see whether this can improve the performance or not.

**Comment by overvenus** [comment]
Just a quick reminder.

 - Unstable Struct std::sync::atomic::AtomicU64
 - [Add more integer atomic types](https://github.com/rust-lang/rust/pull/33048)
 - [rust-rfc: Add more integer atomic types](https://github.com/rust-lang/rfcs/pull/1543)
 - [rust-rfc: Add a generic Atomic\<T\> type] lots of interesting discussion.
 - [atomic-rs], an interesting crate, atomic anything implements `Copy`.

[atomic-rs]: https://github.com/Amanieu/atomic-rs
[rust-rfc: Add a generic Atomic\<T\> type]: https://github.com/rust-lang/rfcs/pull/1505
