### ISSUE TITLE
support output with text and protobuf  format 

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#7]
- [x] Text format
- [x] Protocol buffer format

https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by xiang90** [comment]
```
separate out instrumentation from exposition, allow plugging in protobuf, textformat, or custom serializers as people want
```

**Comment by overvenus** [comment]
Thanks for reminding again :)

**Comment by posix4e** [comment]
What's the story here? We can only put out text. I see some basic protobuf support. Is it just we don't have something fully baked. In the example the client has to bring and setup hyper themselves as far as I can tell.

**Comment by siddontang** [comment]
Hi @posix4e 

I think @xiang90 want us to support these with modularization, so users can determine themselves which one to use easily.
