### ISSUE TITLE
benchmark batch Metric Vector 

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-prometheus#72]
If we want to inc some VecMetric many times, we may first cache in a map then inc in batch. 

```
let m = HashMap::new();
m["a"] += 1
m["b"] += 1
// many times

for (key, value) in &m {
    metric.with_label_values(&[key]).add(value);
}
```

to compare with 

```
 metric.with_label_values(&["a"]).inc(1);
 metric.with_label_values(&["b"]).inc(1);
// many times 
```

**Comment by overvenus** [comment]
I prefer the second one.

Benchmark results are not accurate, if we cache things in a hashmap, because hashmap is relatively [slow](https://www.rust-lang.org/en-US/faq.html#why-are-rusts-hashmaps-slow) in Rust.

**Comment by siddontang** [comment]
Sometimes we can't call the metric too frequently, so we should cache it and call the metric in batch. 
Is HashMap really slow for the above case?
Or we can use BTreeMap or even define a structure for the multi metrics. 
What I want here is to supply a optimization guide for user when they find metrics reduce the performance. 

Btw, Benchmark may be not accurate, but it can still show something for us.
