### ISSUE TITLE
Status of this library and comparison to other prometheus libs in Rust

### ISSUE THREAD

**Issue by kamalmarhubi** [pingcap/rust-prometheus#81]
I'm looking to use Prometheus in a Rust program. There are [a few libraries on crates](https://crates.io/search?q=prometheus). Is this the one that people are coalescing around? It would be good if the README could have some small section stating its status and comparing it to alternatives. A sentence or two would be fine.

**Comment by siddontang** [comment]
Hi @kamalmarhubi 

We have already use our Prometheus Rust lib deeply in TiKV in production, so you can also use it in your project.

We get many help from Prometheus team and you can see our lib in  [Prometheus client libs](https://prometheus.io/docs/instrumenting/clientlibs/).

We may only care two libraries on crates, the one is our's, the other is [metrics](https://crates.io/crates/metrics). `metrics` want to unify some different monitor systems including Prometheus, but we only focus on Prometheus. 

We have many TODOs, it is very appreciated that you can help us :-)

**Comment by kamalmarhubi** [comment]
Closing this, as I've decided this is the most complete library so far. :-)
