### ISSUE TITLE
Allow building without hyper

### ISSUE THREAD

**Issue by kamalmarhubi** [pingcap/rust-prometheus#84]
In the ideal use of Prometheus, libraries provide their own instrumentation:

> The short answer is to instrument everything. Every library, subsystem and service should have at least a few metrics to give you a rough idea of how it is performing.
―https://prometheus.io/docs/practices/instrumentation/

Bringing in the push client by default makes that hard to do: any library instrumented with Prometheus suddenly brings in hyper and all its dependencies.

Here are a couple of ideas on how to fix this:

- make the push gateway client a separate crate
- add an optional feature to enable the push gateway client

**Comment by overvenus** [comment]
I vote the second.

Actually, I used to add a `push` feature in the first place (#53)


What's you opinion? @siddontang

**Comment by kamalmarhubi** [comment]
I also think the crate feature is a better way to go.

**Comment by siddontang** [comment]
I prefer push feature too.

**Comment by overvenus** [comment]
I am working on it, a PR will be sent soon.
