### ISSUE TITLE
Minimize dependencies of the core instrumentation library

### ISSUE THREAD

**Issue by kamalmarhubi** [pingcap/rust-prometheus#85]
This is related to #84. Right now, there are 7 direct dependencies, and 36 transitive dependencies. Removing hyper will go a long way, dropping 21 of the dependencies. The other big improvement we can have is getting rid of regex, which will drop a further 10. With both removed, there would be just 5 dependencies, all of which are direct:

```
fnv (1.0.5)
lazy_static (0.2.1)
libc (0.2.17)
protobuf (1.0.24)
quick-error (0.2.2)
```

**Comment by overvenus** [comment]
For `regex`, maybe we replace it with few handwritten matching functions.

----

We can mark `libc` as optional too, after we adding a `push` feature.

**Comment by kamalmarhubi** [comment]
@overvenus yeah my plan was to replace it with handwritten validators.

**Comment by kamalmarhubi** [comment]
Between #89 and #86 this is pretty much done. Full list of transitive dependencies:

```
fnv         1.0.3
lazy_static 0.2.1
protobuf    1.0
quick-error 0.2
```
